repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run tests for backend
        entry: |
          bash -c '
            if [[ "$OSTYPE" == "linux"* ]];
            then python3 -m unittest discover -s ./backend/tests -p "*.py"
            elif [[ "$OSTYPE" == "msys"* ]];
            then python -m unittest discover -s ./backend/tests -p "*.py";
            fi
          '
        language: system
        pass_filenames: false
        always_run: true